<a href="https://colab.research.google.com/github/kianakiaei/TensorFlow/blob/main/tensorflow_fundamentals_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Create a vector, scalar, matrix and tensor with values of your choosing

scalar = tf.constant([1])
vector = tf.constant([1, 2])
matrix = tf.constant([[1, 2],
                      [3, 4],
                      [5, 6]])
tensor = tf.constant([[[1, 2],
                       [3, 4]],
                      [[5, 6],
                       [7, 8]]])

In [3]:
print("scalar is:", scalar, "\n")
print("vector is:", vector, "\n")
print("matrix is:", matrix, "\n")
print("tensor is:", tensor, "\n")

scalar is: tf.Tensor([1], shape=(1,), dtype=int32) 

vector is: tf.Tensor([1 2], shape=(2,), dtype=int32) 

matrix is: tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) 

tensor is: tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32) 



In [4]:
# Find the shape, rank and size of the tensors you created

print("Shape of tensor is:", tensor.shape)
print("rank of tensor is:", tensor.ndim)
print("size of tensor is:", tf.size(tensor))

Shape of tensor is: (2, 2, 2)
rank of tensor is: 3
size of tensor is: tf.Tensor(8, shape=(), dtype=int32)


In [5]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300]

tf.random.set_seed(42)
a = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
b = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)

In [6]:
a, b

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

In [7]:
# Multiply the two tensors you created in 3 using matrix multiplication.

# First
tf.math.multiply(a, b)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[4.57146466e-01, 2.13658452e-01, 3.28531623e-01, ...,
        2.17384368e-01, 2.51955122e-01, 3.40777524e-02],
       [1.45614594e-01, 3.09705492e-02, 6.57417625e-02, ...,
        2.36865208e-01, 9.56212804e-02, 1.13281950e-01],
       [7.73395528e-04, 1.34753399e-02, 7.99194753e-01, ...,
        1.22185037e-01, 4.81487900e-01, 7.18945917e-03],
       [6.55430436e-01, 5.76979630e-02, 9.58052557e-03, ...,
        6.53199196e-01, 5.08804396e-02, 7.79080987e-01],
       [5.81960231e-02, 1.10622704e-01, 2.62571156e-01, ...,
        6.09022558e-01, 1.02241419e-01, 1.14069067e-01]], dtype=float32)>

In [8]:
# Second
a * b


<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[4.57146466e-01, 2.13658452e-01, 3.28531623e-01, ...,
        2.17384368e-01, 2.51955122e-01, 3.40777524e-02],
       [1.45614594e-01, 3.09705492e-02, 6.57417625e-02, ...,
        2.36865208e-01, 9.56212804e-02, 1.13281950e-01],
       [7.73395528e-04, 1.34753399e-02, 7.99194753e-01, ...,
        1.22185037e-01, 4.81487900e-01, 7.18945917e-03],
       [6.55430436e-01, 5.76979630e-02, 9.58052557e-03, ...,
        6.53199196e-01, 5.08804396e-02, 7.79080987e-01],
       [5.81960231e-02, 1.10622704e-01, 2.62571156e-01, ...,
        6.09022558e-01, 1.02241419e-01, 1.14069067e-01]], dtype=float32)>

In [9]:
# Third
# ?

In [10]:
# Multiply the two tensors you created in 3 using dot product.

# First
tf.matmul(tf.transpose(a), b)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.317161  , 0.61993605, 1.2612379 , ..., 1.5290778 , 1.0735596 ,
        1.6227092 ],
       [1.0170685 , 0.42642498, 0.8181824 , ..., 1.1469344 , 0.8212255 ,
        1.1739546 ],
       [0.45034647, 0.8037954 , 1.4656199 , ..., 1.105671  , 0.88152766,
        1.481925  ],
       ...,
       [1.3204696 , 1.1634867 , 1.7423928 , ..., 1.8386563 , 1.5207756 ,
        1.5979093 ],
       [0.73207504, 0.90400356, 1.8493464 , ..., 1.3821819 , 0.98218614,
        1.924531  ],
       [1.0814031 , 0.5316744 , 0.7174167 , ..., 1.2942287 , 1.0804075 ,
        1.0476992 ]], dtype=float32)>

In [11]:
# Second

tf.transpose(a) @ b

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.317161  , 0.61993605, 1.2612379 , ..., 1.5290778 , 1.0735596 ,
        1.6227092 ],
       [1.0170685 , 0.42642498, 0.8181824 , ..., 1.1469344 , 0.8212255 ,
        1.1739546 ],
       [0.45034647, 0.8037954 , 1.4656199 , ..., 1.105671  , 0.88152766,
        1.481925  ],
       ...,
       [1.3204696 , 1.1634867 , 1.7423928 , ..., 1.8386563 , 1.5207756 ,
        1.5979093 ],
       [0.73207504, 0.90400356, 1.8493464 , ..., 1.3821819 , 0.98218614,
        1.924531  ],
       [1.0814031 , 0.5316744 , 0.7174167 , ..., 1.2942287 , 1.0804075 ,
        1.0476992 ]], dtype=float32)>

In [12]:
# Third

tf.tensordot(tf.transpose(a), b, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.317161  , 0.61993605, 1.2612379 , ..., 1.5290778 , 1.0735596 ,
        1.6227092 ],
       [1.0170685 , 0.42642498, 0.8181824 , ..., 1.1469344 , 0.8212255 ,
        1.1739546 ],
       [0.45034647, 0.8037954 , 1.4656199 , ..., 1.105671  , 0.88152766,
        1.481925  ],
       ...,
       [1.3204696 , 1.1634867 , 1.7423928 , ..., 1.8386563 , 1.5207756 ,
        1.5979093 ],
       [0.73207504, 0.90400356, 1.8493464 , ..., 1.3821819 , 0.98218614,
        1.924531  ],
       [1.0814031 , 0.5316744 , 0.7174167 , ..., 1.2942287 , 1.0804075 ,
        1.0476992 ]], dtype=float32)>

In [13]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

tf.random.set_seed(42)
c = tf.random.uniform(shape=(224, 224, 3), maxval=1, minval=0 )
c

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.42612267, 0.09686017, 0.16105258],
        [0.1487099 , 0.04513884, 0.9497483 ],
        [0.4393103 , 0.28527975, 0.96971095]],

       [[0.73308516, 0.5657046 , 0.33238935],
        [0.8838178 , 0.87544763, 0.56711245],
        [0.8879347 , 0.47661996, 0.42041814],
        ...,
        [0.7716515 , 0.9116473 , 0.3229897 ],
        [0.43050945, 0.83253574, 0.45549798],
        [0.29816985, 0.9639522 , 0.3316357 ]],

       [[0.41132426, 0.2179662 , 0.53570235],
        [0.5112119 , 0.6484759 , 0.8894886 ],
        [0.42459428, 0.20189774, 0.85781324],
        ...,
        [0.02888799, 0.3995477 , 0.11355484],
        [0.68524575, 0.04945195, 0.17778492],
        [0.97627187, 0.79811585, 0.9411576 ]],

       ...,

       [[0.9019445 , 0.27011132, 0.8090267 ],
        [0.32

In [29]:
# Find the min and max values of the tensor you created in 6 along the first axis.

max_c = tf.reduce_max(c, axis=1)
min_c = tf.reduce_min(c, axis=1)

max_c, min_c

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[0.9982879 , 0.991555  , 0.99890864],
        [0.9963852 , 0.99686027, 0.99524415],
        [0.99798036, 0.99789786, 0.9771793 ],
        [0.9925841 , 0.9995371 , 0.996261  ],
        [0.99925447, 0.99854064, 0.98959684],
        [0.99632823, 0.9975462 , 0.9966078 ],
        [0.99893224, 0.99789345, 0.9986447 ],
        [0.99387276, 0.99100804, 0.99803686],
        [0.99614084, 0.99962425, 0.99817014],
        [0.9990084 , 0.99642086, 0.9947417 ],
        [0.99766946, 0.99010587, 0.9985434 ],
        [0.99462116, 0.9989265 , 0.9968679 ],
        [0.9953896 , 0.99844146, 0.997231  ],
        [0.9752687 , 0.99830484, 0.98452115],
        [0.9964744 , 0.99982226, 0.99907696],
        [0.99845874, 0.9961201 , 0.99886775],
        [0.9960511 , 0.99431336, 0.9901949 ],
        [0.99995625, 0.9980805 , 0.99942625],
        [0.97499347, 0.9930481 , 0.9978708 ],
        [0.998369  , 0.99853635, 0.9970608 ],
        [0.9999449 , 0.997383

In [15]:
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

d = tf.random.uniform(shape=(1, 224, 224, 3), maxval=1, minval=0 )

tf.squeeze(d)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.68789124, 0.48447883, 0.9309944 ],
        [0.252187  , 0.73115396, 0.89256823],
        [0.94674826, 0.7493341 , 0.34925628],
        ...,
        [0.10315919, 0.9291539 , 0.99506986],
        [0.51019716, 0.9048054 , 0.22966433],
        [0.6319853 , 0.254349  , 0.6146672 ]],

       [[0.5757792 , 0.06120789, 0.41327834],
        [0.2947657 , 0.06683052, 0.8412062 ],
        [0.9196522 , 0.28208435, 0.88919353],
        ...,
        [0.8421594 , 0.92932725, 0.61236584],
        [0.9058645 , 0.48668993, 0.28548574],
        [0.30320632, 0.06468201, 0.79784656]],

       [[0.4406476 , 0.32621968, 0.03153896],
        [0.65943134, 0.43695068, 0.3716799 ],
        [0.7005588 , 0.81334114, 0.86623895],
        ...,
        [0.26015413, 0.7758442 , 0.32498944],
        [0.81527984, 0.906564  , 0.17323983],
        [0.65714204, 0.83752465, 0.18657303]],

       ...,

       [[0.4058814 , 0.8737236 , 0.9235314 ],
        [0.52

In [16]:
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

d = tf.constant([23, 5, 56, 2, 14, 96, 11, 76, 45, 53])
max_d = d[tf.argmax(d)]
max_d

<tf.Tensor: shape=(), dtype=int32, numpy=96>

In [17]:
# One-hot encode the tensor you created in 9.

tf.one_hot(d, depth=96)

<tf.Tensor: shape=(10, 96), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 